name: '🔍 Storybook PR Preview'

on:
  pull_request:
    types: [opened, reopened, synchronize, closed]

permissions:
  contents: write
  pull-requests: write

concurrency:
  group: preview-${{ github.ref }}
  cancel-in-progress: true

jobs:
  deploy-preview:
    name: '🔍 Deploy PR Preview'
    runs-on: ubuntu-latest
    if: github.event.pull_request.head.repo.fork == false
    steps:
      - name: '📥 Checkout'
        uses: actions/checkout@v4

      - name: '🟢 Setup Node'
        uses: actions/setup-node@v4
        with:
          node-version: 24
          cache: yarn

      - name: '📦 Install dependencies'
        if: github.event.action != 'closed'
        run: yarn install --frozen-lockfile

      - name: '🔨 Build Storybook'
        if: github.event.action != 'closed'
        run: yarn build-storybook

      - name: '🔍 Deploy preview'
        uses: rossjrw/pr-preview-action@ffa7509e91a3ec8dfc2e5536c4d5c1acdf7a6de9 # v1
        with:
          source-dir: ./storybook-static
          preview-branch: gh-pages
          umbrella-dir: pr-preview
          action: auto
          comment: true
          wait-for-pages-deployment: true
